### ISSUE TITLE
Requeriment txt  working

### ISSUE THREAD

**Issue by merlynjocol** [merlynjocol/Covid_Dashboards_OpenData#29]
I checked the libraries inside of the file, and they don't have the version 

1.  Check the libraries the App is using 
- Use: pip freeze in the enviroment 

2. Edit the file

**Comment by merlynjocol** [comment]
from my local machine 

pandas == 1.1.3
numpy == 1.20.0
plotly == 4.14.3
streamlit == 0.81.1

**Comment by merlynjocol** [comment]
This is the message from the deployment in Streamlit: 

⚠️ __ERROR REQUIREMENT__: This is the  current requriment.txt

pip install pandas
pip install numpy
pip install matplotlib
pip install plotly
pip install geopy
pip install streamlit
pip install folium OR conda install -c conda-forge folium
pip install streamlit-folium
pip install altair


**I recomend:  Change the file requerimet.txt to this:**

pandas == 1.1.3
numpy == 1.20.0
plotly == 4.14.3
streamlit == 0.81.1

**Comment by pierrepo** [comment]
Hey :wave: 
Your `requirements.txt` files contains the commands to install each library individually:

```
pip install pandas
pip install numpy
pip install matplotlib
pip install plotly
pip install geopy
pip install streamlit
pip install folium OR conda install -c conda-forge folium
pip install streamlit-folium
pip install altair
```
You should **not** have the `pip install` in this file since you will then install your all dependencies with:
```
pip install -r requirements.txt
```
Also, you cannot mix `pip` and `conda` in this file. `requirements.txt` files are dedicated to pip installs only.

You can indeed provide library versions in the  `requirements.txt` file. It's a good practice!

But to get things easier, I would advise you not to include versions. Your `requirements.txt` file would then look like this:
```
pandas
numpy
matplotlib
plotly
...
```

**Comment by merlynjocol** [comment]
HI Adam, I didn't upload the old file requirement.txt. The old file was using pip, that's why the App couldn't be deployed and get the error.  

I changed the requirements.txt , adding the version of each library, and now is working the App!!! 🥰 

Check the link 🔗 : 

https://share.streamlit.io/merlynjocol/covid_dashboards_opendata/main/covid_opendata.py

__Note__ : Make sure choose a country to start the analysis. Also, I add a Error message and improved the Framework, it is in the last push request
